site_name: Pillar Youtube Uploader

theme:
  name: "material"
  palette:
    scheme: slate
    primary: black
    accent: deep purple
  logo: pillargg.png
  favicon: pillargg.png
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/pillargg/youtube-upload
repo_name: pillargg/youtube-upload

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering: 
          show_sources: false
      watch:
        - youtube_upload